/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTwinsRouteImport } from './routes/app.twins'
import { Route as AppTranscriptRouteImport } from './routes/app.transcript'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'
import { Route as AppReferenceCoverageRouteImport } from './routes/app.reference-coverage'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPoriRouteImport } from './routes/app.pori'
import { Route as AppPathmatchRouteImport } from './routes/app.pathmatch'
import { Route as AppPacketRouteImport } from './routes/app.packet'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppGuideRouteImport } from './routes/app.guide'
import { Route as AppGapsRouteImport } from './routes/app.gaps'
import { Route as AppAdvisorRouteImport } from './routes/app.advisor'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAdvisorRouteImport } from './routes/api/advisor'
import { Route as AppChatIndexRouteImport } from './routes/app.chat.index'
import { Route as AppChatThreadIdRouteImport } from './routes/app.chat.$threadId'
import { Route as ApiV1TranscriptsRouteImport } from './routes/api/v1/transcripts'
import { Route as ApiV1ReferenceRouteImport } from './routes/api/v1/reference'
import { Route as ApiV1PassportRouteImport } from './routes/api/v1/passport'
import { Route as ApiV1PacketsRouteImport } from './routes/api/v1/packets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTwinsRoute = AppTwinsRouteImport.update({
  id: '/app/twins',
  path: '/app/twins',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTranscriptRoute = AppTranscriptRouteImport.update({
  id: '/app/transcript',
  path: '/app/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/app/roadmap',
  path: '/app/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReferenceCoverageRoute = AppReferenceCoverageRouteImport.update({
  id: '/app/reference-coverage',
  path: '/app/reference-coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPoriRoute = AppPoriRouteImport.update({
  id: '/app/pori',
  path: '/app/pori',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPathmatchRoute = AppPathmatchRouteImport.update({
  id: '/app/pathmatch',
  path: '/app/pathmatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPacketRoute = AppPacketRouteImport.update({
  id: '/app/packet',
  path: '/app/packet',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/app/guide',
  path: '/app/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGapsRoute = AppGapsRouteImport.update({
  id: '/app/gaps',
  path: '/app/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/app/advisor',
  path: '/app/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorRoute = ApiAdvisorRouteImport.update({
  id: '/api/advisor',
  path: '/api/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/app/chat/',
  path: '/app/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/app/chat/$threadId',
  path: '/app/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TranscriptsRoute = ApiV1TranscriptsRouteImport.update({
  id: '/api/v1/transcripts',
  path: '/api/v1/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReferenceRoute = ApiV1ReferenceRouteImport.update({
  id: '/api/v1/reference',
  path: '/api/v1/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PassportRoute = ApiV1PassportRouteImport.update({
  id: '/api/v1/passport',
  path: '/api/v1/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PacketsRoute = ApiV1PacketsRouteImport.update({
  id: '/api/v1/packets',
  path: '/api/v1/packets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/gaps': typeof AppGapsRoute
  '/app/guide': typeof AppGuideRoute
  '/app/login': typeof AppLoginRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/packet': typeof AppPacketRoute
  '/app/pathmatch': typeof AppPathmatchRoute
  '/app/pori': typeof AppPoriRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reference-coverage': typeof AppReferenceCoverageRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transcript': typeof AppTranscriptRoute
  '/app/twins': typeof AppTwinsRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/packets': typeof ApiV1PacketsRoute
  '/api/v1/passport': typeof ApiV1PassportRoute
  '/api/v1/reference': typeof ApiV1ReferenceRoute
  '/api/v1/transcripts': typeof ApiV1TranscriptsRoute
  '/app/chat/$threadId': typeof AppChatThreadIdRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/gaps': typeof AppGapsRoute
  '/app/guide': typeof AppGuideRoute
  '/app/login': typeof AppLoginRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/packet': typeof AppPacketRoute
  '/app/pathmatch': typeof AppPathmatchRoute
  '/app/pori': typeof AppPoriRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reference-coverage': typeof AppReferenceCoverageRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transcript': typeof AppTranscriptRoute
  '/app/twins': typeof AppTwinsRoute
  '/app': typeof AppIndexRoute
  '/api/v1/packets': typeof ApiV1PacketsRoute
  '/api/v1/passport': typeof ApiV1PassportRoute
  '/api/v1/reference': typeof ApiV1ReferenceRoute
  '/api/v1/transcripts': typeof ApiV1TranscriptsRoute
  '/app/chat/$threadId': typeof AppChatThreadIdRoute
  '/app/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/gaps': typeof AppGapsRoute
  '/app/guide': typeof AppGuideRoute
  '/app/login': typeof AppLoginRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/packet': typeof AppPacketRoute
  '/app/pathmatch': typeof AppPathmatchRoute
  '/app/pori': typeof AppPoriRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reference-coverage': typeof AppReferenceCoverageRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transcript': typeof AppTranscriptRoute
  '/app/twins': typeof AppTwinsRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/packets': typeof ApiV1PacketsRoute
  '/api/v1/passport': typeof ApiV1PassportRoute
  '/api/v1/reference': typeof ApiV1ReferenceRoute
  '/api/v1/transcripts': typeof ApiV1TranscriptsRoute
  '/app/chat/$threadId': typeof AppChatThreadIdRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/advisor'
    | '/api/chat'
    | '/api/waitlist'
    | '/app/advisor'
    | '/app/gaps'
    | '/app/guide'
    | '/app/login'
    | '/app/onboarding'
    | '/app/packet'
    | '/app/pathmatch'
    | '/app/pori'
    | '/app/profile'
    | '/app/reference-coverage'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/transcript'
    | '/app/twins'
    | '/app/'
    | '/api/v1/packets'
    | '/api/v1/passport'
    | '/api/v1/reference'
    | '/api/v1/transcripts'
    | '/app/chat/$threadId'
    | '/app/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/advisor'
    | '/api/chat'
    | '/api/waitlist'
    | '/app/advisor'
    | '/app/gaps'
    | '/app/guide'
    | '/app/login'
    | '/app/onboarding'
    | '/app/packet'
    | '/app/pathmatch'
    | '/app/pori'
    | '/app/profile'
    | '/app/reference-coverage'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/transcript'
    | '/app/twins'
    | '/app'
    | '/api/v1/packets'
    | '/api/v1/passport'
    | '/api/v1/reference'
    | '/api/v1/transcripts'
    | '/app/chat/$threadId'
    | '/app/chat'
  id:
    | '__root__'
    | '/'
    | '/api/advisor'
    | '/api/chat'
    | '/api/waitlist'
    | '/app/advisor'
    | '/app/gaps'
    | '/app/guide'
    | '/app/login'
    | '/app/onboarding'
    | '/app/packet'
    | '/app/pathmatch'
    | '/app/pori'
    | '/app/profile'
    | '/app/reference-coverage'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/transcript'
    | '/app/twins'
    | '/app/'
    | '/api/v1/packets'
    | '/api/v1/passport'
    | '/api/v1/reference'
    | '/api/v1/transcripts'
    | '/app/chat/$threadId'
    | '/app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdvisorRoute: typeof ApiAdvisorRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppGapsRoute: typeof AppGapsRoute
  AppGuideRoute: typeof AppGuideRoute
  AppLoginRoute: typeof AppLoginRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPacketRoute: typeof AppPacketRoute
  AppPathmatchRoute: typeof AppPathmatchRoute
  AppPoriRoute: typeof AppPoriRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferenceCoverageRoute: typeof AppReferenceCoverageRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTranscriptRoute: typeof AppTranscriptRoute
  AppTwinsRoute: typeof AppTwinsRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiV1PacketsRoute: typeof ApiV1PacketsRoute
  ApiV1PassportRoute: typeof ApiV1PassportRoute
  ApiV1ReferenceRoute: typeof ApiV1ReferenceRoute
  ApiV1TranscriptsRoute: typeof ApiV1TranscriptsRoute
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/twins': {
      id: '/app/twins'
      path: '/app/twins'
      fullPath: '/app/twins'
      preLoaderRoute: typeof AppTwinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transcript': {
      id: '/app/transcript'
      path: '/app/transcript'
      fullPath: '/app/transcript'
      preLoaderRoute: typeof AppTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/app/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reference-coverage': {
      id: '/app/reference-coverage'
      path: '/app/reference-coverage'
      fullPath: '/app/reference-coverage'
      preLoaderRoute: typeof AppReferenceCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pori': {
      id: '/app/pori'
      path: '/app/pori'
      fullPath: '/app/pori'
      preLoaderRoute: typeof AppPoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pathmatch': {
      id: '/app/pathmatch'
      path: '/app/pathmatch'
      fullPath: '/app/pathmatch'
      preLoaderRoute: typeof AppPathmatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/packet': {
      id: '/app/packet'
      path: '/app/packet'
      fullPath: '/app/packet'
      preLoaderRoute: typeof AppPacketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/guide': {
      id: '/app/guide'
      path: '/app/guide'
      fullPath: '/app/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/gaps': {
      id: '/app/gaps'
      path: '/app/gaps'
      fullPath: '/app/gaps'
      preLoaderRoute: typeof AppGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/advisor': {
      id: '/app/advisor'
      path: '/app/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor': {
      id: '/api/advisor'
      path: '/api/advisor'
      fullPath: '/api/advisor'
      preLoaderRoute: typeof ApiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/app/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/$threadId': {
      id: '/app/chat/$threadId'
      path: '/app/chat/$threadId'
      fullPath: '/app/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/transcripts': {
      id: '/api/v1/transcripts'
      path: '/api/v1/transcripts'
      fullPath: '/api/v1/transcripts'
      preLoaderRoute: typeof ApiV1TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reference': {
      id: '/api/v1/reference'
      path: '/api/v1/reference'
      fullPath: '/api/v1/reference'
      preLoaderRoute: typeof ApiV1ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/passport': {
      id: '/api/v1/passport'
      path: '/api/v1/passport'
      fullPath: '/api/v1/passport'
      preLoaderRoute: typeof ApiV1PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/packets': {
      id: '/api/v1/packets'
      path: '/api/v1/packets'
      fullPath: '/api/v1/packets'
      preLoaderRoute: typeof ApiV1PacketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdvisorRoute: ApiAdvisorRoute,
  ApiChatRoute: ApiChatRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  AppAdvisorRoute: AppAdvisorRoute,
  AppGapsRoute: AppGapsRoute,
  AppGuideRoute: AppGuideRoute,
  AppLoginRoute: AppLoginRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPacketRoute: AppPacketRoute,
  AppPathmatchRoute: AppPathmatchRoute,
  AppPoriRoute: AppPoriRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferenceCoverageRoute: AppReferenceCoverageRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTranscriptRoute: AppTranscriptRoute,
  AppTwinsRoute: AppTwinsRoute,
  AppIndexRoute: AppIndexRoute,
  ApiV1PacketsRoute: ApiV1PacketsRoute,
  ApiV1PassportRoute: ApiV1PassportRoute,
  ApiV1ReferenceRoute: ApiV1ReferenceRoute,
  ApiV1TranscriptsRoute: ApiV1TranscriptsRoute,
  AppChatThreadIdRoute: AppChatThreadIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
