import type { User } from "@supabase/supabase-js";
import type {
  CounselorPacketPayload,
  CreditMapping,
  GapAnalysis,
  GapAnalysisPayload,
  GapRequirement,
  GuideArticle,
  GuideTopic,
  PassportSummary,
  Roadmap,
  RoadmapItem,
  RoadmapPayload,
  StudentProfile,
  Transcript,
  TranscriptCourse,
  TranscriptCourseCandidate,
  TranscriptReview,
} from "@/lib/scholaport-api";
import type { Country, Jurisdiction, ReferenceCoverage } from "@/lib/reference-api";

const now = "2026-07-16T16:00:00.000Z";
const userId = "00000000-0000-4000-8000-000000000001";
const profileId = "00000000-0000-4000-8000-000000000002";
const transcriptId = "00000000-0000-4000-8000-000000000003";
const analysisId = "00000000-0000-4000-8000-000000000004";
const roadmapId = "00000000-0000-4000-8000-000000000005";
const packetId = "00000000-0000-4000-8000-000000000006";
const frameworkId = "00000000-0000-4000-8000-000000000007";

export const visualQaUser: User = {
  id: userId,
  aud: "authenticated",
  role: "authenticated",
  email: "visual-qa@scholaport.invalid",
  email_confirmed_at: now,
  confirmed_at: now,
  last_sign_in_at: now,
  app_metadata: { provider: "email", providers: ["email"] },
  user_metadata: { visual_qa_fixture: true },
  identities: [],
  created_at: now,
  updated_at: now,
  is_anonymous: false,
};

export const visualQaProfile: StudentProfile = {
  id: profileId,
  user_id: userId,
  first_name: "Maya",
  last_name: "Rao",
  origin_country: "India",
  source_curriculum: "Tamil Nadu State Board HSC (Class 11-12)",
  destination_country: "United States",
  target_state: "Georgia",
  target_district: "Fulton County Schools",
  target_school: "Northview High School",
  target_program: "General diploma pathway",
  grade_at_transfer: 11,
  expected_graduation_year: 2027,
  preferred_language: "en",
  source_country_id: "00000000-0000-4000-8000-000000000008",
  source_jurisdiction_id: "00000000-0000-4000-8000-000000000009",
  source_curriculum_id: "00000000-0000-4000-8000-000000000010",
  destination_country_id: "00000000-0000-4000-8000-000000000011",
  destination_jurisdiction_id: "00000000-0000-4000-8000-000000000012",
  destination_framework_id: frameworkId,
  destination_program_id: null,
  source_jurisdiction_label: "Tamil Nadu",
  destination_country_label: "United States",
  destination_jurisdiction_label: "Georgia",
  destination_framework_label: "Georgia High School Diploma",
  destination_program_label: null,
  applicable_cohort: "Class of 2027",
  framework_version_label: "2026–27 planning reference",
  created_at: now,
  updated_at: now,
};

export const visualQaTranscript: Transcript = {
  id: transcriptId,
  user_id: userId,
  student_profile_id: profileId,
  original_filename: "maya-rao-grade-10-transcript.pdf",
  file_type: "application/pdf",
  storage_path: `${userId}/${transcriptId}/maya-rao-grade-10-transcript.pdf`,
  upload_status: "processed",
  status: "confirmed",
  ocr_status: "completed",
  ocr_provider: "google_document_ai",
  ocr_started_at: now,
  ocr_completed_at: now,
  ocr_error: null,
  ocr_error_code: null,
  ocr_error_message: null,
  ocr_error_stage: null,
  ocr_raw_text: "Typed visual QA fixture transcript text.",
  ocr_confidence: 0.96,
  ocr_page_count: 2,
  ocr_language_codes: ["en"],
  primary_language_code: "en",
  translation_status: "not_needed",
  translation_provider: null,
  translation_started_at: null,
  translation_completed_at: null,
  translation_error: null,
  translated_text_en: null,
  translation_confidence: null,
  uploaded_file_path: `${userId}/${transcriptId}/maya-rao-grade-10-transcript.pdf`,
  uploaded_file_name: "maya-rao-grade-10-transcript.pdf",
  uploaded_file_mime_type: "application/pdf",
  uploaded_file_size_bytes: 482_000,
  processing_status: "completed",
  processing_stage: "review_complete",
  processing_error_code: null,
  processing_error_message: null,
  processing_started_at: now,
  processing_completed_at: now,
  requires_manual_entry: false,
  ai_extraction_status: "completed",
  ai_extraction_provider: "openai",
  ai_extraction_model: "fixture",
  ai_extraction_error: null,
  ai_extraction_error_code: null,
  ai_extraction_error_message: null,
  detected_language_codes: ["en"],
  detected_source_country_id: visualQaProfile.source_country_id,
  detected_source_jurisdiction_id: visualQaProfile.source_jurisdiction_id,
  detected_source_curriculum_id: visualQaProfile.source_curriculum_id,
  detected_source_country: "India",
  detected_source_jurisdiction: "Tamil Nadu",
  detected_source_curriculum: "Tamil Nadu State Board HSC (Class 11-12)",
  detected_document_type: "secondary_school_transcript",
  profile_match_status: "matched",
  profile_match_confidence: 0.97,
  requires_source_confirmation: false,
  selected_source_country_id: visualQaProfile.source_country_id,
  selected_source_jurisdiction_id: visualQaProfile.source_jurisdiction_id,
  selected_source_curriculum_id: visualQaProfile.source_curriculum_id,
  source_selection_method: "student_override",
  framework_match_status: "confirmed",
  framework_match_confidence: 0.95,
  requires_user_confirmation: false,
  confirmed_at: now,
  confirmation_status: "confirmed",
  detected_source_country_label: "India",
  detected_source_jurisdiction_label: "Tamil Nadu",
  detected_source_curriculum_label: "Tamil Nadu State Board HSC (Class 11-12)",
  selected_source_country_label: "India",
  selected_source_jurisdiction_label: "Tamil Nadu",
  selected_source_curriculum_label: "Tamil Nadu State Board HSC (Class 11-12)",
  created_at: now,
  updated_at: now,
};

export const visualQaCourses: TranscriptCourse[] = [
  ["English Language and Literature", "English / Language Arts", "English", 1, "A"],
  ["Mathematics Standard", "Algebra II", "Mathematics", 1, "A-"],
  ["Science", "Integrated Science", "Science", 1, "B+"],
  ["Social Science", "World History", "Social Studies", 1, "A"],
  ["Information Technology", "Computer Science Foundations", "Elective", 0.5, "A"],
].map(([original, translated, subject, credits, grade], index) => ({
  id: `00000000-0000-4000-8000-${String(20 + index).padStart(12, "0")}`,
  transcript_id: transcriptId,
  course_name_original: String(original),
  course_name_translated: String(translated),
  course_name_normalized: String(translated).toLowerCase(),
  original_language_code: "en",
  translated_language_code: "en",
  subject_category: String(subject),
  credits: Number(credits),
  credits_or_units: "credits",
  grade_original: String(grade),
  grade_normalized: 4,
  grade_scale_original: "letter",
  max_marks: null,
  term_label_original: "2025–26",
  term_label_translated: "2025–26",
  academic_year_label: "2025–26",
  academic_year: 2026,
  grade_level: 10,
  page_number: index < 3 ? 1 : 2,
  source_text: String(original),
  translated_source_text: String(translated),
  extraction_confidence: 0.94 - index * 0.02,
  translation_confidence: 0.97,
  entry_method: "ocr_ai_extracted",
  student_confirmed: true,
  needs_review: index === 4,
  review_reason: index === 4 ? "Destination elective category should be confirmed." : null,
  mapping_status: index === 4 ? "needs_review" : "mapped",
}));

export const visualQaCandidates: TranscriptCourseCandidate[] = visualQaCourses.map(
  (course, index) => ({
    id: `00000000-0000-4000-8000-${String(30 + index).padStart(12, "0")}`,
    transcript_id: transcriptId,
    user_id: userId,
    course_name_original: course.course_name_original,
    course_name_translated: course.course_name_translated,
    course_name_normalized: course.course_name_normalized ?? null,
    original_language_code: course.original_language_code ?? "en",
    translated_language_code: course.translated_language_code ?? "en",
    subject_category: course.subject_category,
    grade_original: course.grade_original,
    grade_normalized: course.grade_normalized ?? null,
    grade_scale_original: course.grade_scale_original ?? null,
    max_marks: course.max_marks ?? null,
    credits_or_units: course.credits_or_units ?? null,
    term_label_original: course.term_label_original ?? null,
    term_label_translated: course.term_label_translated ?? null,
    academic_year: course.academic_year_label ?? null,
    grade_level: course.grade_level ?? null,
    page_number: course.page_number ?? null,
    source_text: course.source_text ?? null,
    translated_source_text: course.translated_source_text ?? null,
    extraction_confidence: course.extraction_confidence ?? null,
    translation_confidence: course.translation_confidence ?? null,
    entry_method: course.entry_method ?? "ocr_ai_extracted",
    student_confirmed: true,
    needs_review: index === 4,
    review_reason: index === 4 ? "Destination elective category should be confirmed." : null,
    created_at: now,
    updated_at: now,
  }),
);

export const visualQaMappings: CreditMapping[] = visualQaCourses.map((course, index) => ({
  id: `00000000-0000-4000-8000-${String(40 + index).padStart(12, "0")}`,
  user_id: userId,
  transcript_id: transcriptId,
  transcript_course_id: course.id,
  student_profile_id: profileId,
  destination_requirement_id: `00000000-0000-4000-8000-${String(60 + index).padStart(12, "0")}`,
  original_course_name: course.course_name_original,
  translated_course_name: course.course_name_translated,
  normalized_course_name: course.course_name_normalized,
  source_subject_category: course.subject_category,
  mapped_subject_category: course.subject_category,
  probable_destination_equivalent: course.course_name_translated,
  requirement_bucket: course.subject_category,
  possible_credit_value: course.credits,
  credit_unit: "Carnegie unit",
  mapping_confidence: index < 2 ? "high" : index < 4 ? "medium" : "low",
  mapping_method: "rules_plus_review",
  mapping_status: index === 4 ? "needs_counselor_review" : "student_confirmed",
  counselor_review_required: index === 4,
  review_reason: index === 4 ? "Confirm local elective placement." : null,
  evidence_summary: "Course title, grade level, and source curriculum were compared.",
  student_note: null,
  counselor_note: null,
  created_at: now,
  updated_at: now,
}));

export const visualQaAnalysis: GapAnalysis = {
  id: analysisId,
  user_id: userId,
  student_profile_id: profileId,
  transcript_id: transcriptId,
  total_credits_required: 23,
  total_credits_mapped: 16.5,
  overall_status: "needs_review",
  analysis_summary: "Most core coursework is represented; two requirements need planning.",
  credit_mapping_run_id: "00000000-0000-4000-8000-000000000080",
  destination_framework_id: frameworkId,
  status: "completed",
  overall_risk_level: "yellow",
  total_likely_earned_credits: 16.5,
  total_possible_earned_credits: 18,
  total_missing_credits: 5,
  high_confidence_credits: 9,
  medium_confidence_credits: 6.5,
  low_confidence_credits: 1,
  unclear_credits: 1.5,
  satisfied_requirement_count: 4,
  partial_requirement_count: 2,
  missing_requirement_count: 1,
  counselor_review_requirement_count: 1,
  assessment_gap_count: 0,
  local_review_required: true,
  summary_text: "Core progress is strong. Focus next on U.S. History and a local elective review.",
  student_next_steps_json: [
    "Bring the IT syllabus to your counselor meeting.",
    "Confirm the U.S. History course sequence for grade 11.",
  ],
  counselor_questions_json: ["Can Information Technology satisfy a local elective requirement?"],
  warnings_json: ["This is a planning preview, not an official evaluation."],
  completed_at: now,
  updated_at: now,
  created_at: now,
};

export const visualQaRequirements: GapRequirement[] = [
  ["English / Language Arts", 4, 4, 0, "satisfied", "green", "complete"],
  ["Mathematics", 4, 3, 1, "partially_satisfied", "yellow", "partial"],
  ["Science", 4, 3, 1, "partially_satisfied", "yellow", "partial"],
  ["Social Studies", 3, 2, 1, "missing", "red", "missing"],
  ["Health & Physical Education", 1, 1, 0, "satisfied", "green", "complete"],
  ["Electives", 4, 3.5, 0.5, "needs_counselor_review", "gray", "review"],
].map(([subject, required, mapped, remaining, status, risk, note], index) => ({
  id: `00000000-0000-4000-8000-${String(90 + index).padStart(12, "0")}`,
  gap_analysis_id: analysisId,
  user_id: userId,
  subject_category: String(subject),
  credits_required: Number(required),
  credits_mapped: Number(mapped),
  credits_remaining: Number(remaining),
  status: String(status),
  priority: index === 3 ? "high" : "medium",
  notes: String(note),
  suggested_actions: Number(remaining) ? [`Plan ${remaining} additional credit.`] : [],
  requirement_category: String(subject),
  requirement_type: "credit",
  requirement_name: String(subject),
  required_amount: Number(required),
  earned_likely_amount: Number(mapped),
  earned_possible_amount: Number(mapped),
  earned_review_amount: status === "needs_counselor_review" ? 0.5 : 0,
  missing_amount: Number(remaining),
  unit_type: "credits",
  risk_level: String(risk),
  matched_credit_mapping_ids: visualQaMappings.slice(index, index + 1).map((item) => item.id),
  supporting_course_names: visualQaCourses
    .slice(index, index + 1)
    .map((item) => item.course_name_original),
  unclear_course_names: status === "needs_counselor_review" ? ["Information Technology"] : [],
  counselor_review_required: status === "needs_counselor_review",
  review_reason: status === "needs_counselor_review" ? "Local elective policy varies." : null,
  requirement_notes: "Destination framework planning row.",
  student_explanation: Number(remaining)
    ? "This requirement still needs a course plan."
    : "Likely covered.",
  counselor_question:
    status === "needs_counselor_review" ? "Can this count as a local elective?" : null,
  display_order: index,
}));

export const visualQaRoadmap: Roadmap = {
  id: roadmapId,
  user_id: userId,
  student_profile_id: profileId,
  gap_analysis_id: analysisId,
  transcript_id: transcriptId,
  destination_country_id: visualQaProfile.destination_country_id,
  destination_jurisdiction_id: visualQaProfile.destination_jurisdiction_id,
  destination_framework_id: frameworkId,
  destination_program_id: null,
  expected_graduation_year: 2027,
  grade_at_transfer: 11,
  title: "Maya’s Georgia graduation roadmap",
  estimated_graduation_date: "2027-05-28",
  is_on_track: true,
  status: "active",
  roadmap_type: "graduation_planning",
  overall_risk_level: "yellow",
  timeline_urgency: "this_semester",
  planning_horizon: "Grade 11 through graduation",
  total_items: 5,
  completed_items: 1,
  critical_items: 1,
  high_priority_items: 2,
  medium_priority_items: 2,
  low_priority_items: 1,
  counselor_review_items: 2,
  summary_text: "Resolve the local elective question first, then lock the remaining core schedule.",
  timeline_summary: "One current action, two next-term courses, and one graduation check.",
  student_next_steps_json: ["Book a counselor meeting", "Bring the IT syllabus"],
  counselor_questions_json: ["Which U.S. History course should Maya take first?"],
  assumptions_json: ["Current grade placement remains grade 11."],
  warnings_json: ["School scheduling and official credit decisions remain local."],
  stale_reason: null,
  completed_at: null,
  generated_at: now,
  created_at: now,
  updated_at: now,
};

export const visualQaRoadmapItems: RoadmapItem[] = [
  [
    "Bring IT syllabus to counselor",
    "Clarify local elective placement.",
    "counselor_meeting",
    "now",
    "high",
    "in_progress",
    "Electives",
  ],
  [
    "Register for U.S. History",
    "Address the remaining Social Studies requirement.",
    "course_registration",
    "next_term",
    "high",
    "todo",
    "Social Studies",
  ],
  [
    "Choose final lab science",
    "Confirm the grade 11 science sequence.",
    "course_registration",
    "next_term",
    "medium",
    "todo",
    "Science",
  ],
  [
    "Confirm senior math sequence",
    "Keep the graduation math plan on track.",
    "course_registration",
    "later",
    "medium",
    "todo",
    "Mathematics",
  ],
  [
    "Review graduation audit",
    "Recheck the official school record before senior spring.",
    "graduation_review",
    "later",
    "low",
    "todo",
    "Planning",
  ],
].map(([title, description, action, timing, priority, status, subject], index) => ({
  id: `00000000-0000-4000-8000-${String(120 + index).padStart(12, "0")}`,
  roadmap_id: roadmapId,
  user_id: userId,
  student_profile_id: profileId,
  gap_requirement_id: visualQaRequirements[index % visualQaRequirements.length].id,
  destination_requirement_id: null,
  credit_mapping_id: null,
  title: String(title),
  description: String(description),
  subject_category: String(subject),
  credits_needed: index === 0 ? null : 1,
  semester_target:
    timing === "now"
      ? "Current semester"
      : timing === "next_term"
        ? "Fall 2026"
        : "Before graduation",
  priority: String(priority),
  completion_method: "student_update",
  action_type: String(action),
  timing_bucket: String(timing),
  suggested_term: timing === "next_term" ? "Fall 2026" : null,
  suggested_grade_level: timing === "later" ? 12 : 11,
  due_window_label: timing === "now" ? "Before course registration" : null,
  required_before: null,
  requirement_category: String(subject),
  risk_level: priority === "high" ? "yellow" : "green",
  counselor_review_required: index < 2,
  counselor_question: index < 2 ? "Confirm this step at the next meeting." : null,
  student_instructions: String(description),
  evidence_note: "Generated from the saved visual QA gap row.",
  completion_note: null,
  display_order: index,
  completed_at: index === 0 ? now : null,
  status: index === 0 ? "done" : String(status),
  order_index: index,
  created_at: now,
  updated_at: now,
}));

export const visualQaPassport: PassportSummary = {
  profile: visualQaProfile,
  transcript: visualQaTranscript,
  gapAnalysis: visualQaAnalysis,
  gapRequirements: visualQaRequirements,
  roadmap: visualQaRoadmap,
  roadmapItems: visualQaRoadmapItems,
};

export const visualQaGapPayload: GapAnalysisPayload = {
  analysis: visualQaAnalysis,
  requirements: visualQaRequirements,
  profile: visualQaProfile,
  transcript: visualQaTranscript,
  transcriptCourses: visualQaCourses,
  creditMappings: visualQaMappings,
};

export const visualQaRoadmapPayload: RoadmapPayload = {
  roadmap: visualQaRoadmap,
  items: visualQaRoadmapItems,
  profile: visualQaProfile,
  transcript: visualQaTranscript,
  transcriptCourses: visualQaCourses,
  creditMappings: visualQaMappings,
  gapAnalysis: visualQaAnalysis,
  gapRequirements: visualQaRequirements,
};

export const visualQaReview: TranscriptReview = {
  transcript: visualQaTranscript,
  candidates: visualQaCandidates,
  profile: visualQaProfile,
};

const packetSnapshot = {
  title: "Academic transfer planning packet",
  generatedAt: now,
  disclaimerText: "Planning preview only. The receiving school makes final decisions.",
  summaryText: "A concise handoff of Maya’s source record, likely mappings, gaps, and next steps.",
  sections: [
    {
      key: "identity",
      title: "Student and academic identity",
      order: 1,
      status: "complete",
      data: { student: "Maya Rao", source: "Tamil Nadu State Board HSC", destination: "Georgia" },
    },
    {
      key: "courses",
      title: "Confirmed transcript courses",
      order: 2,
      status: "complete",
      data: visualQaCourses.slice(0, 3).map((course) => ({
        course: course.course_name_original,
        likelyFit: course.course_name_translated,
      })),
    },
    {
      key: "gaps",
      title: "Graduation coverage preview",
      order: 3,
      status: "review",
      data: visualQaRequirements.slice(0, 4).map((item) => ({
        requirement: item.subject_category,
        status: item.status,
        remaining: item.credits_remaining,
      })),
    },
    {
      key: "roadmap",
      title: "Planning checkpoints",
      order: 4,
      status: "complete",
      data: visualQaRoadmapItems
        .slice(0, 3)
        .map((item) => ({ action: item.title, timing: item.semester_target })),
    },
  ],
  warnings: ["One elective mapping needs counselor review."],
  counselorQuestions: [
    "Can Information Technology satisfy a local elective requirement?",
    "Which U.S. History sequence best fits grade 11?",
  ],
};

export const visualQaPacketPayload: CounselorPacketPayload = {
  ...visualQaRoadmapPayload,
  roadmapItems: visualQaRoadmapItems,
  packet: {
    id: packetId,
    user_id: userId,
    student_profile_id: profileId,
    transcript_id: transcriptId,
    credit_mapping_run_id: visualQaAnalysis.credit_mapping_run_id,
    gap_analysis_id: analysisId,
    roadmap_id: roadmapId,
    destination_country_id: visualQaProfile.destination_country_id,
    destination_jurisdiction_id: visualQaProfile.destination_jurisdiction_id,
    destination_framework_id: frameworkId,
    file_url: null,
    status: "ready",
    packet_type: "counselor_preview",
    packet_version: "1",
    title: packetSnapshot.title,
    summary_text: packetSnapshot.summaryText,
    disclaimer_text: packetSnapshot.disclaimerText,
    packet_snapshot_json: packetSnapshot,
    included_sections: packetSnapshot.sections.map((section) => section.key),
    included_sections_json: packetSnapshot.sections,
    missing_sections_json: [],
    warnings_json: packetSnapshot.warnings,
    counselor_questions_json: packetSnapshot.counselorQuestions,
    source_summary_json: [],
    generated_file_storage_path: null,
    generated_file_mime_type: null,
    generated_file_size_bytes: null,
    generated_file_hash: null,
    printable_html_storage_path: null,
    pdf_generation_error: null,
    stale_reason: null,
    generated_at: now,
    completed_at: now,
    created_at: now,
    updated_at: now,
  },
  packetSections: [],
};

export const visualQaGuideTopics: GuideTopic[] = [
  [
    "credits",
    "Credits and graduation",
    "How course credits build toward graduation.",
    "Planning",
    "Chart",
    6,
  ],
  [
    "counselors",
    "Working with your counselor",
    "What to bring and which questions to ask.",
    "People",
    "People",
    5,
  ],
  [
    "gpa",
    "GPA without the mystery",
    "A practical explanation of weighted and unweighted GPA.",
    "Academics",
    "Book",
    7,
  ],
  [
    "schedule",
    "Reading your school schedule",
    "Periods, semesters, and course levels explained.",
    "First week",
    "Calendar",
    4,
  ],
  [
    "activities",
    "Activities and belonging",
    "How clubs, sports, and service fit into school life.",
    "Community",
    "Flag",
    5,
  ],
  [
    "records",
    "Keeping academic evidence",
    "What documents help with credit review.",
    "Records",
    "Stamp",
    4,
  ],
].map(([slug, title, description, category, icon, minutes], index) => ({
  id: `00000000-0000-4000-8000-${String(150 + index).padStart(12, "0")}`,
  slug: String(slug),
  title: String(title),
  description: String(description),
  category: String(category),
  icon_name: String(icon),
  reading_time_minutes: Number(minutes),
  order_index: index,
  is_published: true,
}));

export const visualQaGuideArticle: GuideArticle = {
  id: "00000000-0000-4000-8000-000000000170",
  topic_id: visualQaGuideTopics[0].id,
  language: "en",
  title: visualQaGuideTopics[0].title,
  content:
    "Credits are the units schools use to record completed coursework. Your counselor can confirm how each transferred course appears on the official record.",
  key_takeaways: [
    "Keep source syllabi",
    "Ask which credits are official",
    "Recheck the graduation audit after changes",
  ],
  is_published: true,
};

const coverageCountry = (index: number, name: string, iso2: string, iso3: string) => ({
  country: {
    id: `00000000-0000-4000-8000-${String(180 + index).padStart(12, "0")}`,
    name,
    iso2,
    iso3,
    region: index === 0 ? "South Asia" : "North America",
    primary_languages: index === 0 ? ["English", "Hindi"] : ["English"],
    education_system_summary: null,
    grade_structure: {},
    is_source_priority: index === 0,
    is_destination_priority: index === 1,
    priority_rank_source: index === 0 ? 1 : null,
    priority_rank_destination: index === 1 ? 1 : null,
    coverage_status: "verified" as const,
    created_at: now,
    updated_at: now,
  },
  mvpVisibility: (index === 0 ? "source" : "destination") as "source" | "destination",
  jurisdictions: index === 0 ? 8 : 51,
  curricula: index === 0 ? 4 : 2,
  curriculumCourses: index === 0 ? 42 : 18,
  frameworks: index === 0 ? 0 : 51,
  requirements: index === 0 ? 0 : 386,
  programs: index === 0 ? 0 : 12,
  dataSources: index === 0 ? 14 : 92,
});

export const visualQaReferenceCoverage: ReferenceCoverage[] = [
  coverageCountry(0, "India", "IN", "IND"),
  coverageCountry(1, "United States", "US", "USA"),
];

export const visualQaSourceCountries: Country[] = [visualQaReferenceCoverage[0].country];
export const visualQaDestinationCountries: Country[] = [visualQaReferenceCoverage[1].country];
export const visualQaSourceJurisdictions: Jurisdiction[] = [
  {
    id: visualQaProfile.source_jurisdiction_id!,
    country_id: visualQaSourceCountries[0].id,
    parent_jurisdiction_id: null,
    name: "Tamil Nadu",
    jurisdiction_type: "state",
    code: "TN",
    education_authority_name: "Directorate of Government Examinations, Tamil Nadu",
    website_url: null,
    coverage_status: "verified",
    is_selectable_for_planning: true,
    identity_verification_status: "verified",
    detail_coverage_status: "verified",
    controls_statewide_graduation_requirements: true,
    local_requirements_may_exceed: false,
    statewide_course_catalog_status: "available",
    jurisdiction_notes: null,
    created_at: now,
    updated_at: now,
  },
];
